[
  {
    "id": 1,
    "first": "Enda",
    "last": "Bubu",
    "department": "MuleSoft"
  },
  {
    "id": 2,
    "first": "Sami",
    "last": "Teee",
    "department": "Software Engineering"
  },
  {
    "id": 3,
    "first": "Memu",
    "last": "Deee",
    "department": "Mathematics"
  }
]